[book]
authors = ["Christian Kaestner"]
language = "en"
src = "src"
title = "Modern Club Passing"


[build]
extra-watch-dirs = ["vizsiteswap"] 

[preprocessor.siteswapsvg]
command = "deno run -A vizsiteswap/mdbook-siteswapsvg.ts"

#[preprocessor.compatsiteswaps]
#command = "compatsiteswaps/mdbook-compatsiteswaps"

[output.linkcheck2]
follow-web-links = false
exclude = [ 'juggling\.tv' ]
warning-policy = "warn"
optional=true

[output.html]
additional-css = ["css/svgstyle.css", "css/bookstyle.css"]
additional-js = ["vizsiteswap/dist/animations.js","vizsiteswap/dist/svg.min.js"]
smart-punctuation = true
git-repository-url = "https://github.com/ckaestne/modernpassing"
git-repository-icon = "fab-github"
default-theme = "light"


#[output.typst]
#[output.typst.output]
#format = "pdf"
