[book]
authors = ["Christian Kaestner"]
language = "en"
multilingual = false
src = "src"
title = "Modern Club Passing"

[preprocessor.siteswapsvg]
command = "node vizsiteswap/dist/mdbook-siteswapsvg.js"

[preprocessor.compatsiteswaps]
command = "node compatsiteswaps/dist/mdbook-compatsiteswaps.js"

[output.html]
additional-css = [".mdbook/svgstyle.css"]
smart-punctuation = true

#[output.typst]
#[output.typst.output]
#format = "pdf"
