name: github pages

on:
  push:
    branches:
      - main
  pull_request:


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: v2.x
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@ee69d230fe19748b7abf22df32acaa93833fad08 # v2
        with:
          mdbook-version: '0.4.52'
          # mdbook-version: 'latest'

      - name: Install mdbook-linkcheck
        run: cargo install mdbook-linkcheck --version 0.7.7 --locked

      - name: Install vizsiteswap dependencies and run tests
        run: cd vizsiteswap; deno install; deno test -A; deno task gen-runtime
        #; deno task build

      - name: Install compatsiteswaps dependencies
        run: cd compatsiteswaps; deno install
        #; deno task build

      - run: mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: ./book/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
